#!/bin/sh

#
# Copyright 2015-2016 Docktitude
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DEB_JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
RPM_JRE_HOME=/usr/lib/jvm/jre-1.8.0-openjdk

JRE_HOME=
if [ -d $DEB_JRE_HOME ]; then
  JRE_HOME=$DEB_JRE_HOME
elif [ -d $RPM_JRE_HOME ]; then
  JRE_HOME=$RPM_JRE_HOME
fi

JAVA_PATH=
if [ ${#JRE_HOME} -eq 0 ] ; then
  JAVA_PATH=java
else
  JAVA_PATH=$JRE_HOME/bin/java
fi

$JAVA_PATH -jar /usr/lib/docktitude/docktitude.jar $@
